#!/usr/bin/bash


username=$(whoami) 

Fstep=/home/$username/Fstep
if test -d "$Fstep"; then
	    echo "$Fstep exists."
    else
	    sudo mkdir /home/$username/Fstep
fi



os_info(){

	os_info_dir=/home/$username/Fstep/OS_INFO
	if test -d "$os_info_dir"; then
		    echo "$os_info_dir exists."
	    else
		    sudo mkdir /home/$username/Fstep/OS_INFO
	fi



	cat /etc/os-release > /home/$username/Fstep/OS_INFO/os_release.txt
	uname -a > /home/$username/Fstep/OS_INFO/name.txt 
	hostnamectl > /home/$username/Fstep/OS_INFO/hostnamectl.txt 

	echo " ================================================================================================================================================="

echo " Uptime of system:"

uptime > /home/$username/Fstep/OS_INFO/uptime.txt 


echo " =================================================================================================================================================="


}

user(){

	user_info_dir=/home/$username/Fstep/USER_INFO
	if test -d "$user_info_dir"; then
		    echo "$user_info_dir exists."
	    else
		    sudo mkdir /home/$username/Fstep/USER_INFO
	fi



	echo " Who Login:"

	who -Hu > /home/$username/Fstep/USER_INFO/user.txt 
	grep sh$ /etc/passwd > /home/$username/Fstep/USER_INFO/user_terminal.txt 


echo "==================================================================================================================================================="


}


check_vm(){

	vm_info_dir=/home/$username/Fstep/VM
	if test -d "$vm_info_dir"; then
		    echo "$vm_info_dir exists."
	    else
		    sudo mkdir /home/$username/Fstep/VM
	fi


	echo "check system is VM or Phisical:"

	sudo dmidecode -s system-manufacturer > /home/$username/Fstep/VM/manufacturer.txt
	sudo dmidecode -s system-product-name > /home/$username/Fstep/VM/product_name.txt
	sudo lshw -c system | grep product | head -1 > /home/$username/Fstep/VM/hardaware.txt
	sudo cat /sys/class/dmi/id/product_name > /home/$username/Fstep/VM/pruduct_name2.txt
	sudo cat /sys/class/dmi/id/sys_vendor > /home/$username/Fstep/VM/system_vendor.txt

	echo "===================================================================================================================================================="


 }


checK_hardware(){

	hw_info_dir=/home/$username/Fstep/HardWare
	if test -d "$hw_info_dir"; then
		    echo "$hw_info_dir exists."
	    else
		    sudo mkdir /home/$username/Fstep/HardWare
	fi



	echo "Check Hardware of System:"

	sudo cat /proc/cpuinfo > /home/$username/Fstep/HardWare/cpuinfo.txt

	sudo cat /proc/meminfo > /home/$username/Fstep/HardWare/memory_info.txt

	ifconfig -a > /home/$username/Fstep/HardWare/interface_configuration.txt

	sudo lshw > /home/$username/Fstep/HardWare/all_hw.txt

	sudo lspci > /home/$username/Fstep/HardWare/pci.txt

	sudo dmidecode > /home/$username/Fstep/HardWare/dmidecode.txt


	echo "======================================================================================================================================================="



}

programs(){

	app_info_dir=/home/$username/Fstep/APP
	if test -d "$app_info_dir"; then
		    echo "$app_info_dir exists."
	    else
		    sudo mkdir /home/$username/Fstep/APP
	fi


	echo "check whitch Program installed on System:"

	sudo rpm -qa > /home/$username/Fstep/APP/what_istalled.txt
	sudo yum repolist > /home/$username/Fstep/APP/repolist.txt
	sudo yum repoinfo > /home/$username/Fstep/APP/repositoru_info.txt

	echo "======================================================================================================================================================="


}

process(){
	process_info_dir=/home/$username/Fstep/Process
	if test -d "$process_info_dir"; then
		    echo "$process_info_dir exists."
	    else
		    sudo mkdir /home/$username/Fstep/Process
	fi


	echo "Check Process and Service on System:"

	sudo pstree -pa 1 > /home/$username/Fstep/Process/pstree.txt
	sudo ps -ef > /home/$username/Fstep/Process/precess.txt
	sudo ps auxf > /home/$username/Fstep/Process/full_process.txt


	echo "========================================================================================================================================================"



}

network(){

	net_info_dir=/home/$username/Fstep/Network
	if test -d "$net_info_dir"; then
		    echo "$net_info_dir exists."
	    else
		    sudo mkdir /home/$username/Fstep/Network
	fi


	
	echo "Check Network Connections:"


	sudo netstat -tulpn > /home/$username/Fstep/Network/network_conections.txt
	echo "=================================================================================" > /home/$username/Fstep/Network/network_connections.txt
	echo "============================Detail===============================================" > /home/$username/Fstep/Network/network_connections.txt


	sudo netstat -anp > /home/$username/Fstep/Network/network_connections.txt

	sudo lsof -i > /home/$username/Fstep/Network/openFiles.txt

	sudo ss > /home/$username/Fstep/Network/socket.txt

	cat /etc/resolv.conf > /home/$username/Fstep/Network/resolv.txt


	echo "=========================================================================================================================================================="


}

kernel(){


	kernel_info_dir=/home/$username/Fstep/Kernel
	if test -d "$kernel_info_dir"; then
		    echo "$kernel_info_dir exists."
	    else
		    sudo mkdir /home/$username/Fstep/Kernel
	fi


	echo "Check Kernel Modules:"

	lsmod > /home/$username/Fstep/Kernel/Kernel_Modules.txt


	echo "==========================================================================================================================================================="

}



logs(){

	log_info_dir=/home/$username/Fstep/LOG
	if test -d "$log_info_dir"; then
		    echo "$log_info_dir exists."
	    else
		    sudo mkdir /home/$username/Fstep/LOG
	fi


	echo "Check Logs:"

	sudo dmesg > /home/$username/Fstep/LOG/dmesg.txt

	sudo journalctl > /home/$username/Fstep/LOG/journal.txt


	echo "============================================================================================================================================================"


}


Firewall(){

	firewall_info_dir=/home/$username/Fstep/Firewall
	if test -d "$firewall_info_dir"; then
		    echo "$firewall_info_dir exists."
	    else
		    sudo mkdir /home/$username/Fstep/Firewall
	fi



	sudo iptables_save >  /home/$username/Fstep/Firewall/iptables_dump.txt 


}
